# Generated by Django 5.1.2 on 2024-10-14 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0023_remove_message_recaptcha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competence',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='education',
            name='the_year',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='education',
            name='title',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='experience',
            name='the_year',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='experience',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
