# Generated by Django 5.1.2 on 2024-10-14 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0024_alter_competence_title_alter_education_the_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competence',
            name='icon',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
