# Generated by Django 5.1.2 on 2024-10-14 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0025_competence_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competence',
            name='image',
            field=models.FileField(blank=True, upload_to='competence/'),
        ),
    ]
