# Generated by Django 5.1.2 on 2024-10-14 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0026_alter_competence_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competence',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
