# Generated by Django 5.1.2 on 2024-10-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0027_alter_competence_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competence',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='competence',
            name='image',
            field=models.FileField(upload_to='competence/'),
        ),
    ]
