# Generated by Django 5.1.2 on 2024-10-15 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0028_alter_competence_description_alter_competence_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competence',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='competence/'),
        ),
    ]
