# Generated by Django 5.1.2 on 2024-10-15 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0029_alter_competence_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competence',
            name='icon',
            field=models.CharField(blank=True, default='fa-brands fa-2xl', max_length=200),
        ),
    ]
