# Generated by Django 5.1.2 on 2024-10-15 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0030_alter_competence_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
