# Generated by Django 5.1.2 on 2024-10-15 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0031_alter_education_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competence',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
