# Generated by Django 5.1.2 on 2024-10-15 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0032_alter_competence_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competence',
            name='image',
        ),
    ]
