# Generated by Django 5.1.2 on 2024-10-15 02:32

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0033_remove_competence_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
                ('description', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(upload_to='research/')),
                ('tools', models.CharField(max_length=200)),
                ('demo', models.URLField()),
                ('github', models.URLField()),
                ('show_in_slider', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='information',
            name='googlescholar',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
