# Generated by Django 5.1.2 on 2024-10-15 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0034_research_information_googlescholar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='facebook',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='github',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='googlescholar',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='instagram',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='linkedin',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='twitter',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
