# Generated by Django 5.1.2 on 2024-10-15 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0035_alter_information_facebook_alter_information_github_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competence',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='competence/'),
        ),
    ]
