# Generated by Django 5.1.2 on 2024-10-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0036_competence_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='competence',
            name='type',
            field=models.CharField(choices=[('programming_language', 'Programming Language'), ('framework', 'Framework'), ('front_end', 'Front-End'), ('database', 'Database'), ('devops', 'DevOps'), ('data_visualization', 'Data Visualization')], default='programming_language', max_length=50),
        ),
    ]
