# Generated by Django 5.1.2 on 2024-10-15 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0037_competence_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='research',
            name='tools',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
