# Generated by Django 5.1.2 on 2024-10-16 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0038_research_file_alter_research_tools'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
