# Generated by Django 3.0.7 on 2021-01-10 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=30)),
                ('LastName', models.CharField(max_length=30)),
                ('Age', models.CharField(max_length=30)),
                ('Nationality', models.CharField(max_length=30)),
                ('Freelance', models.CharField(default='Available', max_length=30)),
                ('Address', models.CharField(max_length=30)),
                ('Phone', models.CharField(max_length=14)),
                ('Email', models.CharField(max_length=30)),
                ('Linkedin', models.CharField(max_length=30)),
                ('Github', models.CharField(max_length=30)),
                ('Languages', models.CharField(max_length=30)),
            ],
        ),
    ]
