# Generated by Django 3.0.7 on 2021-01-13 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_auto_20210113_0109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nos', models.CharField(max_length=10)),
                ('Dsc', models.CharField(max_length=40)),
            ],
        ),
    ]
