# Generated by Django 3.0.7 on 2021-01-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_keys'),
    ]

    operations = [
        migrations.CreateModel(
            name='Key4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('No1', models.CharField(max_length=10)),
                ('Dsc1', models.CharField(max_length=40)),
                ('No2', models.CharField(max_length=10)),
                ('Dsc2', models.CharField(max_length=40)),
                ('No3', models.CharField(max_length=10)),
                ('Dsc3', models.CharField(max_length=40)),
                ('No4', models.CharField(max_length=10)),
                ('Dsc4', models.CharField(max_length=40)),
            ],
        ),
        migrations.DeleteModel(
            name='Keys',
        ),
    ]
