# Generated by Django 3.0.7 on 2021-01-13 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_auto_20210113_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skilset', models.CharField(max_length=10)),
                ('value', models.IntegerField(max_length=10)),
            ],
        ),
    ]
