# Generated by Django 3.0.7 on 2021-01-14 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skilset', models.CharField(max_length=10)),
                ('value', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.CharField(max_length=20)),
                ('Title', models.CharField(max_length=40)),
                ('Dsc', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.CharField(max_length=20)),
                ('Title', models.CharField(max_length=40)),
                ('Dsc', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Framework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skilset', models.CharField(max_length=10)),
                ('value', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='FrontBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skilset', models.CharField(max_length=10)),
                ('value', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skilset', models.CharField(max_length=10)),
                ('value', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
