# Generated by Django 3.1.5 on 2021-01-15 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0010_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pdf',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
