# Generated by Django 4.0.4 on 2024-02-17 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0011_post_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='Dsc',
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='education',
            name='Time',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='education',
            name='Title',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='education',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='experience',
            name='Dsc',
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='experience',
            name='Time',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='experience',
            name='Title',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='experience',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
