# Generated by Django 4.0.4 on 2024-02-17 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0012_alter_education_dsc_alter_education_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='Age',
            field=models.IntegerField(max_length=30),
        ),
    ]
