# Generated by Django 4.0.4 on 2024-02-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0013_alter_resume_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='Nationality',
            new_name='Location',
        ),
        migrations.AlterField(
            model_name='resume',
            name='Address',
            field=models.CharField(max_length=300),
        ),
    ]
